version: '3.8'

services:
  spring:
    container_name: spring
    image: DOCKER_USERNAME/softalk-spring
    expose:
      - 8080
    ports:
      - 8080:8080

  nginx:
    container_name: nginx
    image: DOCKER_USERNAME/softalk-nginx
    ports:
      - 80:80
    depends_on:
      - spring